# Generated by Django 4.2.4 on 2023-11-02 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_alter_analyse_maximum_alter_analyse_minimum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyse',
            old_name='points',
            new_name='metric',
        ),
        migrations.RemoveField(
            model_name='analyse',
            name='banda',
        ),
        migrations.RemoveField(
            model_name='analyse',
            name='cross',
        ),
        migrations.RemoveField(
            model_name='analyse',
            name='rsi',
        ),
    ]
